---
name: module3_task2

on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  check_build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd module3_task2
          chmod u+x setup.sh
          ./setup.sh

      - name: Build
        run: |
          cd module3_task2
          make build

      - name: Generating package
        run: |
          cd module3_task2
          make package

      - name: Archive package
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: awesome-website
          path: module3_task2/awesome-website.zip
